### ISSUE TITLE
remove batch effect?

### ISSUE THREAD

**Issue by Roger-GOAT** [RausellLab/CelliD#11]
Hi team, I go through the CelliD Vignette and found there is no API to remove the batch effect. So the cell of each sample is in a different position in tSNE or UMAP. Where did I miss? Thanks for your help.

**Comment by Cortalak** [comment]
Hello sorry for the delay.

CelliD doesn't have a batch effect correction method _per se_. The signatures extracted by CellID are good enough that genes impacted by technical factors (batch effect) are not included in.
If you want to correct the UMAP or tSNE you will have to use other solutions proposed for Seurat or SingleCellExperiment Object.

Seurat has batch effect correction functions or external compatible packages such as Harmony.
For SingleCellExperiment users I recommend batchelor package from bioconductor.
