### ISSUE TITLE
minSize in RunCellHGT

### ISSUE THREAD

**Issue by hsmith9002** [RausellLab/CelliD#12]
I am getting the error 
`All pathways have less than minSize features in common with the data` even wen mizSize is = 1. I imagine this is more of an issue on my end, but could you give a little more detail on how this argument works, and why I might be getting this error, so I can trouble shoot on my end.

One thing to note is that I haven't yet manually annotated the clusters in my Seurat Object (i.e. they are still just numbered). In the CelliD vingette, the clusters in your example data are already annotated. Is that necessary?

Thank you
Harry

**Comment by Cortalak** [comment]
Hi Harry, 

Should not be a problem having the Seurat cluster number as they normally a factor and not numeric class.

It is very probable that the signature name doesnt match with the gene names in your Seurat or SingleCellExperiment object.  Happened to me when I missed the fact that I extacted signatures from ensembl gene id annotated data and tested against single cell data using gene symbols, or mouse gene symbols against human. 

minSize is filtering all signatures that has less than that minSize genes/features in common with the genes used to compute mca.

you can maybe try to find the number of genes finding a match with the mca genes with something like this.
`lapply(gene_signatures,function(x) sum(x %in% rownames(seurat_object@reductions$mca@feature.loadings)))`

**Comment by hsmith9002** [comment]
The gene names in the panglao data set were formatted differently than in my seurat object. Once I fixed that, the function runs successfully. Thank you for your help. Feel free to close.

Harry
