### ISSUE TITLE
NA values returned after applying CellID (c)

### ISSUE THREAD

**Issue by singlecellfan** [RausellLab/CelliD#14]
Hi,

thanks for this great tool. On the first sight it works nicely. 
I have one problem however. After running everything according to your vignette, there are "NA" values returned for some cells. These are different from the "unassigned" ones.

![Screenshot 2022-10-19 at 10 58 36](https://user-images.githubusercontent.com/79158757/196645765-4a44d6cd-e901-45a9-ac71-fdbff8616fd4.png)

I have confirmed that these "NA" cells were in the object prior to running CellID. So I am not sure why there not assigned any label
Has this problem occurred before?

Thank you much in advance!

**Comment by singlecellfan** [comment]
Turns out, there was an issue with the data. Sorry for that.

**Comment by trantunhi99** [comment]
hi, can you please share what is the possibility of the data problem that lead to NA in the result?
