### ISSUE TITLE
Error: cannot allocate vector of size 4.5 Gb

### ISSUE THREAD

**Issue by dKlee99** [RausellLab/CelliD#7]
After running `covidProt <- covid[rownames(covid) %in% HgProteinCodingGenes,]` this code, I got following error `Error: cannot allocate vector of size 4.5 Gb` Would it be possible to solve this error?

**Comment by Cortalak** [comment]
Hi,

This is mostly linked with total RAM usage exceeding the capacity of your machine.
In that case there's nothing I can really do on my side to solve the error.
The matrix you are loading is too big to be handled by your machine, so you will need a server able to handle such big matrix.

**Comment by tilofrei** [comment]
@dKlee99 there is some [advice on stackoverflow](https://stackoverflow.com/questions/5171593/r-memory-management-cannot-allocate-vector-of-size-n-mb) that is largely dependent on your setup. Hope that helps
