### ISSUE TITLE
installing issue with R 4.0.4

### ISSUE THREAD

**Issue by AlexandrePelletier** [RausellLab/CelliD#9]
Hi Akira, 
I'm trying to install CelliD legacy version on R4.0.4 but that raise an error : 

"ERROR: this R is version 4.0.4, package 'CelliD' requires R >= 4.1"

Have you any solution for this issue ?

 I used then on my personal computer with R 4.1, and it work fine, but I would like to install it on the Lab server now.
Thanks for this Package, very helpful for my works !

Best,
Alexandre (from sinCellTE Roscoff 2020)

**Comment by Cortalak** [comment]
Hi Alexandre,

I just tried with a fresh R 4.0.4 installation on windows and it worked.
Did you really try to install the legacy version and not the latest one?
`devtools::install_github("RausellLab/CelliD", ref = "legacy")`

normally the error 
"ERROR: this R is version 4.0.4, package 'CelliD' requires R >= 4.1"
only occurs with bioconductor installation or the regular github installation `devtools::install_github("RausellLab/CelliD")`

Best regards,

Akira

**Comment by AlexandrePelletier** [comment]
Indeed My bad, this error come from the non legacy version. 
With the legacy version i have this error : 
Error: (converted from warning) package ‘Seurat’ was built under R version 4.0.5

**Comment by Cortalak** [comment]
This is a recurrent error I have seen in may packages. The warning is actually considered as an error and stops the installation.
Unfortunately I only found a workaround right now but normally it should not have any consequences on the package integrity.
This code should bypasss the warning.
`Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)`

**Comment by AlexandrePelletier** [comment]
Ok that works with this code, thanks a lot !
